# Generated by Django 4.2.5 on 2023-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_type", models.CharField(blank=True, max_length=50, null=True)),
                ("c_description", models.CharField(max_length=50)),
                ("c_date", models.DateField()),
                ("c_lat", models.DecimalField(decimal_places=9, max_digits=15)),
                ("c_lon", models.DecimalField(decimal_places=9, max_digits=15)),
                ("c_city", models.CharField(max_length=30)),
                ("c_state", models.CharField(max_length=3)),
            ],
        ),
    ]
