# Generated by Django 4.2.5 on 2023-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="c_description",
            field=models.CharField(max_length=50, verbose_name="Crime Description"),
        ),
        migrations.AlterField(
            model_name="crime",
            name="c_lat",
            field=models.DecimalField(
                decimal_places=9, max_digits=15, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="c_lon",
            field=models.DecimalField(
                decimal_places=9, max_digits=15, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="c_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Crime Type"
            ),
        ),
    ]
