# Generated by Django 4.2.5 on 2023-09-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dash_app", "0003_alter_crime_c_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "e_description",
                    models.CharField(
                        max_length=200, verbose_name="Scene/Evidence Description"
                    ),
                ),
                ("e_date", models.DateField(verbose_name="Date")),
                (
                    "e_lat",
                    models.DecimalField(
                        decimal_places=9, max_digits=15, verbose_name="Latitude"
                    ),
                ),
                (
                    "e_lon",
                    models.DecimalField(
                        decimal_places=9, max_digits=15, verbose_name="Longitude"
                    ),
                ),
                (
                    "c_correlated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dash_app.crime",
                    ),
                ),
            ],
        ),
    ]
