# Generated by Django 4.2.5 on 2023-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_app", "0004_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="c_description",
            field=models.CharField(max_length=100, verbose_name="Crime Description"),
        ),
    ]
